### ISSUE TITLE
Destroy not working with Firefox 40.0.3 (Mobile First 7.1)

### ISSUE THREAD

**Issue by kashban** [MobileFirst-Platform-Developer-Center/JSONStore#1]
I tried using WL.JSONStore.destroy() in one of my projects as per documentation and it fails with "Uncaught Exception: TypeError: meta is null at (compiled_code):1767". 

Same happens with this demo app regardless if a JSONStore is initialized or not. 

This is where the script fails:

```
  _destroy = function(store) {
    var deferred = $.Deferred(),
    metaKeys = [],
    meta,
    usernames = [],
    col,
    patt,
    metadata,
    colIndex,
    metaIndex;

    setTimeout(function () {
      /*jshint forin:false*/
      for(var metaKey in ls) {
        metaIndex = metaKey.indexOf(constant.METADATA_TAG);
        patt = new RegExp('"' + constant.USERNAME + '":', ['g']);
        meta = ls.getItem(metaKey);
          if(meta.match(patt) !== null && metaIndex > -1) {
```

By debugging this part I found that meta is null for metaKey "key". That metaKey isn't even part of ls, so it should not come up anyway. Browser is Firefox 40.0.3.

Worth noting: With Chrome 44.0.2403.157 it works without any hassles, as well as IE 11.0.9600.17959.

Best regards
Jürgen

**Comment by NathanHazout** [comment]
Thank you for reporting this. It seems to be a bug in the JSONStore product itself. 
We're looking into it. APAR PI48467.

**Comment by IdanAdar** [comment]
The APAR has been resolved. The fix will appear in the next iFix release to IBM Fix Central. Let us know if you require it now or can wait until the iFix is out. Closing.

**Comment by kashban** [comment]
Thanks for the quick response. Since I am currently developing a hybrid mobile app Firefox is no big deal for us. The next iFix release will do.
